module.exports = {
    code: 666,
    msg: "success",
    result: [
      {
        detail: "团建订的房间 房间看不到海 但离海边很近",
        hashid: "D7o1517owB",
        headImageURL: "http://static.huruqing.cn/villa/dft_head.png",
        headImgUrl: "http://static.huruqing.cn/villa/dft_head.png",
        houseId: 21012,
        id: 3769,
        images: [
          "http://static.huruqing.cn/villa/3ddYlclApqGYan.jpg",
          "http://static.huruqing.cn/villa/M6605UOxZw3L72.jpg",
          "http://static.huruqing.cn/villa/0xxaASOl5GnJjx.jpg",
          "http://static.huruqing.cn/villa/xvvNkS5n9aLAbq.jpg",
        ],
        nickName: "136****0601",
        score: 5,
        submitDate: "2019-01-30",
        submitTime: "2019-01-30",
      },
      {
        detail: "很舒适，老板人很好，距离海近",
        hashid: "0BZnP1jewz",
        headImageURL:
          "https://wx.qlogo.cn/mmopen/V0mhkIwf3EH16pCgAT7qMDSVicdqpl9cLeomWYx3XLJcD7OT0wV2XW2DqEbYT39v28S87aMaV5oA5tnjcIgjZwA/132",
        headImgUrl:
          "https://wx.qlogo.cn/mmopen/V0mhkIwf3EH16pCgAT7qMDSVicdqpl9cLeomWYx3XLJcD7OT0wV2XW2DqEbYT39v28S87aMaV5oA5tnjcIgjZwA/132",
        houseId: 21711,
        id: 1603,
        images: [],
        nickName: "李杰",
        score: 5,
        submitDate: "2018-05-31",
        submitTime: "2018-05-31",
      },
      {
        detail: "还不错",
        hashid: "vaeDGbZnkz",
        headImageURL:
          "https://wx.qlogo.cn/mmopen/V0mhkIwf3EH16pCgAT7qMDSVicdqpl9cLeomWYx3XLJcD7OT0wV2XW2DqEbYT39v28S87aMaV5oA5tnjcIgjZwA/132",
        headImgUrl:
          "https://wx.qlogo.cn/mmopen/V0mhkIwf3EH16pCgAT7qMDSVicdqpl9cLeomWYx3XLJcD7OT0wV2XW2DqEbYT39v28S87aMaV5oA5tnjcIgjZwA/132",
        houseId: 24860,
        id: 2728,
        images: [],
        nickName: "pandaria🍄  盼",
        score: 5,
        submitDate: "2019-03-03",
        submitTime: "2019-03-03",
      },
      {
        detail: "整体都不错，很齐全！",
        hashid: "QrE7GzkE2z",
        headImageURL: "http://static.huruqing.cn/villa/dft_head.png",
        headImgUrl: "http://static.huruqing.cn/villa/dft_head.png",
        houseId: 63934,
        id: 3622,
        images: [],
        nickName: "匿名",
        score: 5,
        submitDate: "2019-02-17",
        submitTime: "2019-02-17",
      },
      {
        detail:
          "这是我千挑万选的店，非常满意，最好的是房间，和其他民宿不同，床品接近酒店，特别满意。\r\n老板管家们特别贴心，各方面服务都特别周到。\r\n以后有机会一定常去。",
        hashid: "OVe8GZLnZk",
        headImageURL:
          "https://thirdwx.qlogo.cn/mmopen/vi_32/Z19xY2BFzwajoH2PXLPic3JjDGfUZvUIz6icYxQtnZfDibqBuSQbL6PVJnkKsBmpKtgP1ibYb1Zy9wySmopOic2JzLA/132",
        headImgUrl:
          "https://thirdwx.qlogo.cn/mmopen/vi_32/Z19xY2BFzwajoH2PXLPic3JjDGfUZvUIz6icYxQtnZfDibqBuSQbL6PVJnkKsBmpKtgP1ibYb1Zy9wySmopOic2JzLA/132",
        houseId: 21728,
        id: 3424,
        images: [],
        nickName: "EGG  XU",
        score: 5,
        submitDate: "2019-02-16",
        submitTime: "2019-02-16",
      },
      {
        detail: "很喜欢",
        hashid: "MDny5R6nrz",
        headImageURL:
          "https://wx.qlogo.cn/mmopen/fjMlfY2KWcicrSU1OzQ6icf27lHlkZmpdvvIrXiaDhPOVQa4Y3ib0017GbsQuXDZGLTx4yrI3PcX2YAMrX0M0uQx7Q/132",
        headImgUrl:
          "https://wx.qlogo.cn/mmopen/fjMlfY2KWcicrSU1OzQ6icf27lHlkZmpdvvIrXiaDhPOVQa4Y3ib0017GbsQuXDZGLTx4yrI3PcX2YAMrX0M0uQx7Q/132",
        houseId: 32035,
        id: 3334,
        images: [
          "http://static.huruqing.cn/villa/qABe1CM8GoM24b.jpg",
          "http://static.huruqing.cn/villa/D3xZjuPxk9P83A.jpg",
          "http://static.huruqing.cn/villa/MnxLlsOMkGO09w.jpg",
          "http://static.huruqing.cn/villa/pa1PQcZO3YZBpa.jpg",
          "http://static.huruqing.cn/villa/3MR5OClNk3lo9P.jpg",
        ],
        nickName: "Heason",
        score: 5,
        submitDate: "2019-02-04",
        submitTime: "2019-02-04",
      },
      {
        detail: "很好！",
        hashid: "D7o15j5owB",
        headImageURL: "http://static.huruqing.cn/villa/dft_head.png",
        headImgUrl: "http://static.huruqing.cn/villa/dft_head.png",
        houseId: 30151,
        id: 3169,
        images: [],
        nickName: "陈小姐",
        score: 5,
        submitDate: "2019-01-12",
        submitTime: "2019-01-12",
      },
      {
        detail:
          "很不错，卖家人很好，房间干净卫生，位置也很好，很近海边，周边都很方便！",
        hashid: "QrE7GMxE2z",
        headImageURL: "http://static.huruqing.cn/villa/dft_head.png",
        headImgUrl: "http://static.huruqing.cn/villa/dft_head.png",
        houseId: 30151,
        id: 3166,
        images: [
          "http://static.huruqing.cn/villa/pc_comment/20180716104553.jpg",
          "http://static.huruqing.cn/villa/pc_comment/20180716104613.jpg",
          "http://static.huruqing.cn/villa/pc_comment/20180716104614.jpg",
        ],
        nickName: "陈小姐",
        score: 5,
        submitDate: "2019-01-12",
        submitTime: "2019-01-12",
      },
      {
        detail: "1",
        hashid: "1VoO9yAeaA",
        headImageURL: "http://static.huruqing.cn/villa/dft_head.png",
        headImgUrl: "http://static.huruqing.cn/villa/dft_head.png",
        houseId: 21711,
        id: 2143,
        images: ["http://img.villaday.com/images/comment/qABe1CM8GoM24b.jpg",'http://img.villaday.com/images/comment/D3xZjuPxk9P83A.jpg',"http://img.villaday.com/images/comment/MnxLlsOMkGO09w.jpg"],
        nickName: "186****4895",
        score: 5,
        submitDate: "2019-01-05",
        submitTime: "2019-01-05",
      },
      {
        detail:
          "临近海边，去附近觅食、游玩也挺方便的；房间干净整洁，老板很耐心地交代各种注意的地方，事无巨细，人很nice。整体感受不错的，下次有机会还会再来的！！！",
        hashid: "M0oj8m5e37",
        headImageURL: "http://static.huruqing.cn/villa/dft_head.png",
        headImgUrl: "http://static.huruqing.cn/villa/dft_head.png",
        houseId: 21711,
        id: 2096,
        images: [],
        nickName: "杨小姐",
        score: 5,
        submitDate: "2018-12-30",
        submitTime: "2018-12-30",
      },
    ],
  };
  